apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lavinmq-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lavinmq-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lavinmq-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lavinmq-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lavinmq-operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ include "lavinmq-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENABLE_WEBHOOKS
              value: {{ ternary "true" "false" .Values.webhook.enabled | quote }}
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          {{- if .Values.webhook.enabled }}
          ports:
            - containerPort: {{ .Values.webhook.service.targetPort }}
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ .Values.webhook.certSecretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
