apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lavinmq-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lavinmq-operator.labels" . | nindent 4 }}
